name: life_line_gm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.4.0
  intl: ^0.20.2
  flutter_svg: ^2.2.3
  google_fonts: ^8.0.1
  flutter_animate: ^4.5.2
  glassmorphism: ^3.0.0
  provider: ^6.1.5+1
  flutter_dotenv: ^6.0.0
  get_it: ^9.2.0
  #reown_appkit: ^1.8.2
  starknet: ^0.2.0
  web3dart: ^2.7.3
  encrypt: ^5.0.3
  bip39: ^1.0.6
  local_auth: ^3.0.0
  cloud_firestore: ^6.1.2
  minio: ^3.5.8
  mime: ^2.0.0
  path_provider: ^2.1.5
  file_picker: ^10.3.10
  http: ^1.6.0
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  #reown_sign: ^1.3.9
  walletconnect_flutter_v2: ^2.4.1
  walletconnect_modal_flutter: any
  app_links: ^6.4.1
  shared_preferences: ^2.5.4
  crypto: ^3.0.7
  emailjs: ^4.0.0
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

    
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.5
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/images/

dependency_overrides:
  freezed_annotation: ^3.1.0
  pointycastle: ^4.0.0
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  web: ^1.1.0
